### ISSUE TITLE
Sending /train in consecutive messages rewards 4 points per question automatically

### ISSUE THREAD

**Issue by theraggedflygon** [ADawesomeguy/AwesomeSciBo#11]
One can quickly farm points by sending "/train" as a response to a question and the bot will give the user 8 points as a result of marking both of the questions correctly for some reason. This should be preventable by a simple if statement denying the response /train to a question saying how there is already a question active.

**Comment by ADawesomeguy** [comment]
Hey! Thanks for leaving an issue. I'll get on fixing this asap.

**Comment by ADawesomeguy** [comment]
Closing this because the same thing is stated in #15, now that there's newfound interest it's time to figure out why it broke in the latest update of discord.js 13.
