### ISSUE TITLE
Awesome Scibo Responds to self

### ISSUE THREAD

**Issue by Bomjoe** [ADawesomeguy/AwesomeSciBo#17]
When the override button is pressed after a new question is opened with /train awsomescibo sees it's override message as an answer to the /train.

**Comment by ADawesomeguy** [comment]
Thanks! It seems that the message filter that makes sure the answer is sent by the same person that requested the question isn't working. A fix is in the works at the moment.

**Comment by ADawesomeguy** [comment]
Fixed in 0ec3abe8dde6fc98be315ed447d3cfe29d8f5e82
