### ISSUE TITLE
Improvements to Answer Parsing 

### ISSUE THREAD

**Issue by xlq902** [ADawesomeguy/AwesomeSciBo#27]
Make the bot accept answers after `(ACCEPT:` tags

**Comment by xlq902** [comment]
Note: Tried to fix with #12 and #22, but couldn't due to changes in code

**Comment by ADawesomeguy** [comment]
I think the best way to do this would be to use `.split(' (ACCEPT: ')` as this will create a single element array if it doesn't have the "accept" thing at the end, which is what was manually being done earlier anyways. Once you split it, you can check the size to see whether you need to remove the trailing bracket or not.
