### ISSUE TITLE
Rounds do not generate

### ISSUE THREAD

**Issue by xlq902** [ADawesomeguy/AwesomeSciBo#29]
When using /rounds generate, the application does not respond.
<img width="177" alt="image" src="https://user-images.githubusercontent.com/64386991/159168781-3deb33a6-0c95-4bdf-abe3-a64bf9eb7b52.png">

**Comment by ADawesomeguy** [comment]
That is a good point, I'll have to reimplement that. The fact is that it ties into the awesomescibo api, which I think would be best just to merge into this repo.

**Comment by ADawesomeguy** [comment]
Actually, I think this is due to timing out, which was fixed in #23. The rounds are non-functional anyways since the API and the bot have to be running with the same database, which will hopefully be made easier with #30.
