### ISSUE TITLE
User preferences

### ISSUE THREAD

**Issue by ADawesomeguy** [ADawesomeguy/AwesomeSciBo#35]
Allow users to configure their preferences, with a separate collection in the DB dedicated to this.

**Comment by ADawesomeguy** [comment]
@TejasOS it would be cool if you could manage the DB collections and such and I'll manage the user input. Models go in the `models` directory and helper functions can go in `helpers/db.ts`.

**Comment by ADawesomeguy** [comment]
@xlq902 if you want to take a look at this issue, maybe see if you can get multi-select menus working for selecting different preferences. The preferences themselves can be found in `models/userConfig.ts`. Take a look [here](https://discordjs.guide/interactions/select-menus.html#multi-select-menus) to learn more. If you can get the Discord side working, I'll work on the DB stuff.

**Comment by xlq902** [comment]
See https://github.com/ADawesomeguy/AwesomeSciBo/tree/feature-preferences for progress

**Comment by ADawesomeguy** [comment]
DB time 💪🏽

**Comment by ADawesomeguy** [comment]
**FINALLY** done with 48243e61f0eb3c7ae9186c67bf6e4e472a0aa00d.
